// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 28/07/2025, 11:29:20
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/vikas/Downloads/client-management-system (1)/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vikas/Downloads/client-management-system (1)/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vikas/Downloads/client-management-system (1)/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vikas/Downloads/client-management-system (1)/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vikas/Downloads/client-management-system (1)/plugins/**/*.{js,ts,mjs}","/home/vikas/Downloads/client-management-system (1)/composables/**/*.{js,ts,mjs}","/home/vikas/Downloads/client-management-system (1)/utils/**/*.{js,ts,mjs}","/home/vikas/Downloads/client-management-system (1)/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/vikas/Downloads/client-management-system (1)/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/vikas/Downloads/client-management-system (1)/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/vikas/Downloads/client-management-system (1)/app.config.{js,ts,mjs}","/home/vikas/Downloads/client-management-system (1)/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;